version: '3.8'
services:
  app:
    build: .
    networks:
      - my_network
    # Autres configurations du service Express.js

  nginx:
    image: nginx:latest
    networks:
      - my_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
