version: '3.8'
services:
  app:
    build: .
    networks:
      - mysql_network

  nginx:
    image: nginx:{{ nginx_version }}
    networks:
      - mysql_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:{{ mysql_version }}
    networks:
      - mysql_network
    command: --init-file /data/application/init.sql
    volumes:
        - {{ mysql_volumes }}
    environment:
      MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
      MYSQL_DATABASE: {{ mysql_database }}
      MYSQL_USER: {{ mysql_user }}
      MYSQL_PASSWORD: {{ mysql_password }}

networks:
  mysql_network:
    driver: bridge
