version: '3.8'
services:
  app:
    build: .
    networks:
      - mysql_network
    # Autres configurations du service Express.js

  nginx:
    image: nginx:latest
    networks:
      - mysql_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:8.1.0
    networks:
      - mysql_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

  mysql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
